---
title: "InteractiveComplexHeatmap in an R Markdown document"
author: "Zuguang Gu"
date: "16/12/2020"
output: html_document
runtime: shiny
---


```{r}
library(ComplexHeatmap)
library(InteractiveComplexHeatmap)
m = matrix(rnorm(100*100), 100)
ht = Heatmap(m)
```


```{r, echo = FALSE}
ui = fluidPage(
    InteractiveComplexHeatmapOutput()
)

server = function(input, output, session) {
    renderInteractiveComplexHeatmap(ht, input, output, session)
}

shiny::shinyApp(ui, server, options = list(height = 700))
```


The source code of this R Markdown document is:

````markdown
---
title: "InteractiveComplexHeatmap in an Rmarkdown document"
author: "Zuguang Gu"
date: "16/12/2020"
output: html_document
runtime: shiny
---


`r ''````{r, echo=FALSE}
library(InteractiveComplexHeatmap)
m = matrix(rnorm(100*100), 100)
ht = Heatmap(m)
```


`r ''````{r, echo=FALSE}
ui = fluidPage(
    InteractiveComplexHeatmapOutput()
)

server = function(input, output, session) {
    renderInteractiveComplexHeatmap(ht, input, output, session)
}

shiny::shinyApp(ui, server)
```
````
